// Package scaffold creates a small, conventional Android application project.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var packageRe = regexp.MustCompile(`^[a-z][a-z0-9]*(\.[a-z][a-z0-9_]*)+$`)

// nameRe restricts the project display name to a charset that can't break out
// of the Kotlin string literals and the XML attribute value it's interpolated
// into (settings.gradle.kts, AndroidManifest.xml, the generated .kt source).
var nameRe = regexp.MustCompile(`^[\p{L}\p{N} ._-]+$`)

type Options struct {
	Destination string
	Name        string
	Package     string
}

// Create writes a minimal Kotlin Android application project. It intentionally
// does not overwrite an existing non-empty directory.
func Create(opts Options) ([]string, error) {
	if strings.TrimSpace(opts.Destination) == "" {
		return nil, fmt.Errorf("destination is required")
	}
	if !packageRe.MatchString(opts.Package) {
		return nil, fmt.Errorf("package must look like com.example.app")
	}
	if strings.TrimSpace(opts.Name) == "" {
		opts.Name = "Android App"
	}
	if !nameRe.MatchString(opts.Name) {
		return nil, fmt.Errorf("name may contain only letters, digits, spaces, '.', '_', or '-'")
	}
	if entries, err := os.ReadDir(opts.Destination); err == nil && len(entries) > 0 {
		return nil, fmt.Errorf("destination is not empty: %s", opts.Destination)
	} else if err != nil && !os.IsNotExist(err) {
		return nil, err
	}

	className := strings.Trim(strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			return r
		}
		return ' '
	}, opts.Name), " ")
	parts := strings.Fields(className)
	className = "MainActivity"
	if len(parts) > 0 {
		word := strings.Title(strings.ToLower(parts[0]))
		if word[0] >= '0' && word[0] <= '9' {
			word = "App" + word // a leading digit is not a valid Kotlin identifier start
		}
		className = word + "Activity"
	}
	files := map[string]string{
		"settings.gradle.kts": `pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name = "` + opts.Name + `"
include(":app")
`,
		"build.gradle.kts": `plugins {
    id("com.android.application") version "8.7.3" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
}
`,
		"gradle.properties": "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\n",
		"app/build.gradle.kts": `plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android { namespace = "` + opts.Package + `"; compileSdk = 35
    defaultConfig { applicationId = "` + opts.Package + `"; minSdk = 23; targetSdk = 35; versionCode = 1; versionName = "1.0" }
}
`,
		"app/src/main/AndroidManifest.xml": `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:theme="@style/Theme.App" android:label="` + opts.Name + `">
        <activity android:name=".` + className + `" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`,
		"app/src/main/java/" + strings.ReplaceAll(opts.Package, ".", "/") + "/" + className + ".kt": `package ` + opts.Package + `

import android.os.Bundle
import android.widget.TextView
import androidx.activity.ComponentActivity

class ` + className + ` : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(TextView(this).apply { text = "` + opts.Name + `" })
    }
}
`,
		"app/src/main/res/values/styles.xml": `<?xml version="1.0" encoding="utf-8"?>
<resources><style name="Theme.App" parent="android:style/Theme.Material.Light.NoActionBar" /></resources>
`,
		"README.md":  "# " + opts.Name + "\n\nGenerated by adb_mcp. Add the Gradle wrapper with `gradle wrapper` if Gradle is installed.\n",
		".gitignore": ".gradle/\nbuild/\nlocal.properties\n*.iml\n",
	}
	var written []string
	for rel, data := range files {
		path := filepath.Join(opts.Destination, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return written, err
		}
		if err := os.WriteFile(path, []byte(data), 0o644); err != nil {
			return written, err
		}
		written = append(written, path)
	}
	return written, nil
}
